apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/controllers
patches:
  - path: kube-prometheus-stack.yaml
    target:
      kind: HelmRelease
  - path: ingress-nginx.yaml
    target:
      kind: HelmRelease